### ISSUE TITLE
proc-macro-regex fails on ".*"

### ISSUE THREAD

**Issue by DanielT** [LinkTed/proc-macro-regex#1]
I tried to use proc-macro-regex today and unfortunately found a bug:
```
regex!(validator ".*");
```
produces the error:
```
error: proc macro panicked
 --> src\main.rs:4:1
  |
4 | regex!(validator ".*");
  | ^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Error("Could not parse regex: Translate(Error { kind: InvalidUtf8, pattern: \".*\", span: Span(Position(o: 0, l: 1, c: 1), Position(o: 1, l: 1, c: 2)) })")
```

Overall I'm actually quite impressed, proc-macro-regex handled a few complex expressions easily. Failing on .* is a bit awkward though.

**Comment by DanielT** [comment]
After some investigation, I've found that this error is originally triggered by regex_syntax::ParserBuilder

The parser is built like this: let mut parser = ParserBuilder::new().unicode(false).build()
The documentation of ParserBuilder::unicode says:

> Note that unless allow_invalid_utf8 is enabled (it’s disabled by default), a regular expression will **fail to parse** if Unicode mode is
> disabled and a sub-expression could possibly match invalid UTF-8.

So it seems that for byte string input the parser should be built like this
```
ParserBuilder::new().unicode(false).allow_invalid_utf8(true).build()
```
and for string input the parser should be built without .unicode(false)
```
ParserBuilder::new().build()
```

**Comment by LinkTed** [comment]
Hi @DanielT, I fix the bug in 88888e7208a3140f8377c4f8a4a11f742ddabbdd, but caution to use `.` or `\w` because the regex would be big. The reason is that it would match alot of Unicode characters.

**Comment by DanielT** [comment]
Thanks!

**Comment by earthengine** [comment]
Emmm... This need to be improved. I have a single `.*` in the regex and it takes `cargo check` to run 35 minutes just for this bit... have to change to `[a-z0-9A-Z_=-]*`?

**Comment by earthengine** [comment]
I would suggest, the macro should have some configuration settings like `use_external_unicode_classification` or `allow_invalid_utf8` being set differently for user's choice.

(I understand using external unicode classification will require dependency of other components and may not be compatible for `no_std` settings, this is why it should be a config settings)

**Comment by LinkTed** [comment]
> Emmm... This need to be improved. I have a single `.*` in the regex and it takes `cargo check` to run 35 minutes just for this bit... have to change to `[a-z0-9A-Z_=-]*`?

As far as I know, `.` means everything except new line. see [regex documentation](https://docs.rs/regex/latest/regex/#matching-one-character)

Did you try to use a byte string?

```
regex!(example_1 b"[a-z0-9A-Z_=-]+"); 
```

Btw, `.*` will always be true.

**Comment by LinkTed** [comment]
> I would suggest, the macro should have some configuration settings like `use_external_unicode_classification` or `allow_invalid_utf8` being set differently for user's choice.
> 
> (I understand using external unicode classification will require dependency of other components and may not be compatible for `no_std` settings, this is why it should be a config settings)

I do not see a difference, at least for the `.` class. For example, the following function will generate the same code even if `allow_invalid_utf8` is `true` or `false`.
```
regex!(example_1 ".");
```
